# Generated by Django 3.0.7 on 2020-08-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0011_auto_20200819_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names_of_toner_cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('printers', models.ManyToManyField(to='repairs.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('logo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Toner_cartridges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('prefix', models.TextField()),
                ('number', models.IntegerField()),
                ('names', models.ManyToManyField(to='toners.Names_of_toner_cartridge')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repairs.Departments')),
            ],
            options={
                'verbose_name': 'Toner cartridge',
                'unique_together': {('prefix', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Toner_cartridges_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repairs.Locations')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toners.Statuses')),
                ('toner_cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toners.Toner_cartridges')),
            ],
            options={
                'verbose_name': 'Toner cartridges log',
                'verbose_name_plural': 'Toner cartridges log',
            },
        ),
    ]
