# Generated by Django 3.0.7 on 2020-08-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0012_auto_20200824_1306'),
        ('toners', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Names_of_toner_cartridge',
            new_name='NamesOfTonerCartridge',
        ),
        migrations.RenameModel(
            old_name='Toner_cartridges',
            new_name='TonerCartridges',
        ),
        migrations.RenameModel(
            old_name='Toner_cartridges_log',
            new_name='TonerCartridgesLog',
        ),
    ]
