# Generated by Django 3.0.7 on 2020-09-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0002_auto_20200824_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tonercartridges',
            options={'ordering': ['prefix', 'number'], 'verbose_name': 'Toner cartridge'},
        ),
        migrations.AlterModelOptions(
            name='tonercartridgeslog',
            options={'ordering': ['-pk'], 'verbose_name': 'Toner cartridges log', 'verbose_name_plural': 'Toner cartridges log'},
        ),
    ]
